spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prediction?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: wlwl666666
    driver-class-name: com.mysql.jdbc.Driver